export const ACTIONS = {
  JOIN_LIVE: "join-live",
  LEAVE_LIVE: "leave-live",
  ADD_PEER_LIVE: "add-peer-live",
  REMOVE_PEER_LIVE: "remove-peer-live",
  RELAY_ICE_LIVE: "relay-ice-live",
  RELAY_SDP_LIVE: "relay-sdp-live",
  SESSION_DESCRIPTION_LIVE: "session-description-live",
  ICE_CANDIDATE_LIVE: "ice-candidate-live",
  MUTE_LIVE: "mute-live",
  UNMUTE_LIVE: "unmute-live",
  MUTE_INFO_LIVE: "mute-info-live",
  END_LIVE: "end-live",
  BLOCK_USER_LIVE: "block-user-live",
  LIVE_ENDED: "live-ended",
  LIVE_CLIENTS: "live-clients",
  LIVE_ENDED_REDIRECT: "live-ended-redirect",
  ERROR_LIVE: "error-live",
};
